name: Deploy Vue Project to Vercel

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/vercel.yml'
      - 'ps49934_nguyenthanhtruc_asm/**'
  workflow_dispatch:

env:
  PROJECT_NAME: "ps49934_nguyenthanhtruc_asm"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./${{ env.PROJECT_NAME }}
      
      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./${{ env.PROJECT_NAME }}
      
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./${{ env.PROJECT_NAME }}