name: Deploy Vue Project to Vercel

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/vercel.yml'
      - 'ps49934_nguyenthanhtruc_asm/**'
      - '!ps49934_nguyenthanhtruc_asm/README.md'
      - '!ps49934_nguyenthanhtruc_asm/architecture/**'
      - '!ps49934_nguyenthanhtruc_asm/.env'
      - '!ps49934_nguyenthanhtruc_asm/.env.local'
      - '!ps49934_nguyenthanhtruc_asm/.gitignore'
      - '!README.md'
  workflow_dispatch:

env:
  PROJECT_NAME: "ps49934_nguyenthanhtruc_asm"
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./${{ env.PROJECT_NAME }}
      
      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./${{ env.PROJECT_NAME }}
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}
          VITE_JWT_SECRET: ${{ secrets.VITE_JWT_SECRET }}
      
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./${{ env.PROJECT_NAME }}